# Background and foreground colors
background = #002136
foreground = #b8f0e9

# Standard colors
palette = 0=#002136
palette = 1=#f60045
palette = 2=#00bd92
palette = 3=#fb6b00
palette = 4=#009388
palette = 5=#850046
palette = 6=#006b6f
palette = 7=#f9d5a4

# Bright colors
palette = 8=#006b6f
palette = 9=#f60045
palette = 10=#00bd92
palette = 11=#fb6b00
palette = 12=#009388
palette = 13=#850046
palette = 14=#009388
palette = 15=#b8f0e9
