$color = rgba(0, 33, 54, 1.0)
$inner_color = rgba(0, 33, 54, 0.66)
$outer_color = rgba(0, 68, 83, 1.0)
$font_color = rgba(184, 240, 233, 1.0)
$placeholder_color = rgba(184, 240, 233, 0.7)
$check_color = rgba(0, 107, 111, 1.0)
